DROP TABLE IF EXISTS TOKEN;

CREATE TABLE TOKEN (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  token VARCHAR(250) NOT NULL,
);

DROP TABLE IF EXISTS SCORE;
CREATE TABLE SCORE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  move VARCHAR(250),
  total_score NUMBER NOT NULL,
);
